### ISSUE TITLE
[리팩터링] recoil & API 컴포넌트화

### ISSUE THREAD

**Issue by kimmming** [FRONTENDSCHOOL5/final-11-NigoNego#121]
## 컴포넌트화 시켜야하는 곳
`JoinMember.jsx`
### 1. 프로필 설정 API  JoinMemberAPI
- 회원가입이 되는 API 부분 
- username, email, password,accountname 등등 다 받아서 post 하면 회원가입이 되는 부분이다.
![image](https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/48938203/d3a0f733-7fb1-48d4-8aec-ce2158f0c398)

### 2.  프로필 설정 중 이미지 업로드 API
- 프로필 이미지를 업로드 하는 API 이다.
![image](https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/48938203/da5586c4-1347-4e95-8be8-5a684856d106)

**Comment by kimmming** [comment]
## recoil 파일 분리
- `atoms.jsx` 파일에 있던 atom들을 분리하였습니다.
사용하실때 경로를 atoms.jsx 가 아닌 `/authToken.jsx` 이런식이 되도록 해주세요.
- `atoms.jsx` 에 있는 followingAtom은 분리하지 않았는데 following 목록을 상태관리 할 필요가 없어서 하지 않았습니다. 
  - 기존에는 Login 할 때, followingAtom 에 following 이 한명이라도 있을 경우 HomeFeed로 가게 해두었습니다. 
 ![image](https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/48938203/ad9d677e-fdd8-4cf8-8b98-643dd535c57f)

**Comment by kimmming** [comment]
## JoinMemberAPI.jsx + URL.js 
- URL.js 에 API 기본 주소를 적어서 추가하였다.
- `JoinMemberAPI.jsx` 를 생성했다.
---
- `JoinMember.jsx` 에 API 에 전달할 userInfo 객체를 만들었다.
- `JoinMember.jsx` 에서는 구조분해할당으로 다시 각 변수에 할당해주었다.
-  작동안됨

![image](https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/48938203/b88ac9ba-164e-4b7f-9452-0c2cde077407)

**Comment by Oh5Yeonju** [comment]
이슈 마무리 하여 close 합니다.
