### ISSUE TITLE
[필독] 나는 리코일을 어떻게 썻는가..

### ISSUE THREAD

**Issue by kimmming** [FRONTENDSCHOOL5/final-11-NigoNego#122]
현재 recoil atom 으로 Token 뭐 기타등등을 관리하고 있는 **`LoginPage.jsx`** 기준으로 작성하겠습니다.

## Recoil
- Meta 산 상태관리 라이브러리
- 셀렉터랑 뭐랑 많은데 Atom만 썼어요

### atoms
- state 단위로 업데이트 
- 업데이트 되면 이거 가져다 쓰는 컴포넌트들이 재랜더링됨
- atom 함수로 생성

## Recoil - persist : 전역상태가 새로고침하면 증발해요

로그인을 할 때 Token 값을 Recoil state로 넣어 다니는 방식으로 유저 로그인을 체크합니다.
[npm - Recoil-Persist](https://www.npmjs.com/package/recoil-persist)
문제는 페이지를 새로고침하면 **Recoil State가 증발**합니다. 

이걸 해결하기 위해 **Recoil-persist 라이브러리를  사용**하였습니다.
**Recoil-persist**를 사용하면 **recoil state가 날아가지 않고 localStorage에 보관**됩니다.

그렇습니다. Recoil 이 자동적으로 localStorage에 보관되는게 아니었습니다.
Recoil-persist 라이브러리를 사용해서 localStorage에 저장되는 것이었습니다.
3주가 지나서 알았습니다. 자동으로 되는줄..

## atoms.jsx
**atoms.jsx** 입니다. 
`atom` 은 key 와 default 등등으로 되어있습니다.
`key` 는 고유키입니다. 그냥 내맘대로 작명가능합니다.
`default` 는 초기 값입니다. 우리 아톰은 '' 문자열로 되어있습니다.
`effects_UNSTABLE: [persistAtom]` Recoil-persist를 적용시키기 위한 필수 문장입니다. 
![image](https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/48938203/18e95927-55af-47f2-a3ba-233d34f11843)

위 사진에 한 파일에 3개의 atom 이 들어가있는데, 이걸 하나씩 `authAtom.jsx`, `accountName.jsx`  이런식으로 분리 해두었습니다. (제 브랜치에만)

**Comment by kimmming** [comment]
문의@질문 
디스코드 태그로 부탁드립디다

**Comment by kimmming** [comment]
### 그래서 우리는 저 token 값을 어디서 쓸수잇냐

제가 한 곳이 `ProfileEditpage.jsx` 밖에 없어서 이게 기준인데 얘도 야매입니다.
어쨌든 Go

```javascript
  const auth = useRecoilValue(authAtom);
```

위에 auth (= token) 값을 authAtom에서 불러옵니다.
**useRecoilValue: No 함수 Yes 값**

이 auth 값을, API 호출할 때
```javascript
  try {
        // API 요청 보내기
        const response = await axios.put(
          'https://api.mandarin.weniv.co.kr/user',
          {
            user: {
              username: userName,
              accountname: userID,
              intro: userIntro,
              image: userImage, // 사용자 이미지 값}
            },
          },
          {
            headers: {
    *******          Authorization: `Bearer ${auth}`, *********
              'Content-type': 'application/json',
            },
          },
        );
```

이렇게 Authorization 자리에 auth 가 들어가도록 넣어주면 되는 것입니다 ! ! ! 
매우 간단하죠?!?!?

그리고 `accountname`  atom 의 경우에는 지금 `getData.js` 에 작성되어있는

```
// homepost
export const GetMyProfileData = async () => {
  try {
    // id부분 props 로 재작업하기
    // const res = await getDataBase.get(`/post/${id}`);
    const response = await getDataBase.get(`/profile/nigonego`)
    return response
  } catch (err) {
    console.log("오류")
  }
};

```
nigonego를 없애고 저렇게 넣을 수 있겠습니다.

### 이걸 지금까지 왜 못고쳤냐!

1. `APi.jsx` 의 baseUrl의 `Authorization: nigonego 토큰 값`으로 되어있음

- Recoil은 React 함수 안에서 선언 해야 하는데 선언하면 오류났음.
- 함수형으로 만들어서 Authorization: ${auth} 로 변경했는데  이것저것 페이지별 오류 났음
    - `getData.js` 에서 import 해서 getDataBase 로 가져다 쓰고 있음

2. `getData.js` 에서 props 로 재작업하는 부분들에서 id ? accountname? 뭘로 쓰이고 있는지 분간이 안갔었음

- 추적 60분 찍었는데 어디서 오는 accountname인지, 얘가 계정의 accountname 인지 뭔지 분간할 수 없었음

**Comment by snowkwon420** [comment]
확인했습니다 감사합니다~!

**Comment by Oh5Yeonju** [comment]
리코일 작업 마무리 하여 close 합니다.
