### ISSUE TITLE
[회의] 공통 컴포넌트의 width 는 100%로 설정

### ISSUE THREAD

**Issue by suconpa** [FRONTENDSCHOOL5/final-11-NigoNego#36]
공통컴포넌트에 width를 임의대로 설정했을 떄 재사용시 width가 원하는 크기로 설정이 되지않는 문제가 있었습니다.
아래 활성화된 로그인 버튼의 width는 80% 로 설정된 상태이며 이럴 경우 로그인 버튼의 부모 div의 width에 따라 80%를 유지하게 됩니다. 
해당 문제를 해결하기 위해 공통 컴포넌트의 width는 100%로 설정해야합니다.
![image](https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/89624140/eb2564eb-2383-4b85-8dc9-97ecd30bae73)

해당 코드
https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/blob/e6796655e95b6467fcdfc262d82d301775146ece/src/components/common/button/Button.jsx#LL49C1-L101C3

**Comment by kimmming** [comment]
네 좋습니다

**Comment by suconpa** [comment]
develop 에 merge완료
