### ISSUE TITLE
[회의] Input 컴포넌트 경고창 추가할지?

### ISSUE THREAD

**Issue by snowkwon420** [FRONTENDSCHOOL5/final-11-NigoNego#49]
## 경고문구를 input 컴포넌트 안에서 구현할지 아니면 그냥 페이지마다 따로 구현할지 고민해 봅시다!!

- 로그인 페이지

로그인 버튼 클릭할때 경고창 
<img width="404" alt="image" src="https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/85488522/52846ed2-7577-4e93-a03e-6eb264b5241a">

- 회원가입 페이지

다음 버튼 클릭시 경고창 
![image](https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/85488522/7c9708bf-bdb1-47dd-a8d2-5b517678e013)

![image](https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/85488522/7e64ed4f-c77c-436c-94b0-0d5c26ba7f98)

- 프로필 설정 페이지

니고네고 시작하기 버튼 클릭시
![image](https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/85488522/4ab6ce9a-1a8d-4e8b-a16f-972a2c8233c0)

![image](https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/85488522/7a5536e4-0134-4270-bfcb-2f5c45d641ee)

**Comment by snowkwon420** [comment]
@snowkwon420 
@kimmming 
@Oh5Yeonju  
의견 남겨주세요!

**Comment by kimmming** [comment]
경고창 추가 컴포넌트 안에서 해도 될 것 같습니다

**Comment by suconpa** [comment]
컴포넌트 안에 하시죠!
