### ISSUE TITLE
[회의] 리팩토링

### ISSUE THREAD

**Issue by Oh5Yeonju** [FRONTENDSCHOOL5/final-11-NigoNego#74]
1. 이미지 업로드 버튼을 컴포넌트화를 해야 할까요?
포스트업로드, 상품 수정, 프로필 이미지 넣기에서 중복으로 사용하는 '파일 업로드 버튼'을 컴포넌트화 해야 한다는 의견이 있었습니다. 
<img width="194" alt="회의  버튼 컴포넌트화" src="https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/assets/117130358/fb031a26-7b37-4356-9f6c-c0c7018377f3">

**Comment by kimmming** [comment]
넵 컴포넌트화 하면 좋겠습니다
저도 프로필 설정할때 필요해서 postUpload 에 있던 버튼을 복사해와서
common/button/UploadButton 파일에 만들어 두고 썼습니다
https://github.com/FRONTENDSCHOOL5/final-11-NigoNego/blob/feature-72/src/components/common/button/UploadButton.jsx
